template_path: hive-emr.py

parameters:
    KeyName: "gumartinm"
    EMRRole: "EMR_DefaultRole"
    EMRAutoScalingRole: "EMR_AutoScaling_DefaultRole"
    EC2InstanceProfileRole: "EMR_EC2_DefaultRole"
    ReleaseLabel: "emr-5.23.0"
    EC2SubnetId: "subnet-7dfb4a27"
    EMRLogUri: "s3n://gumartinm-emr-logs/hive/"

    AdditionalMasterSecurityGroup: !stack_output dev/simple-security-group.yaml::SimpleSecurityGroup
    MasterSecurityGroup: !stack_output dev/simple-security-group.yaml::SimpleSecurityGroup
    AdditionalSlaveSecurityGroup: !stack_output dev/simple-security-group.yaml::SimpleSecurityGroup
    SlaveSecurityGroup: !stack_output dev/simple-security-group.yaml::SimpleSecurityGroup

    DatabaseAddress: !stack_output dev/maria-db-rds-hive-metastore.yaml::DatabaseAddress
    DatabasePort: !stack_output dev/maria-db-rds-hive-metastore.yaml::DatabasePort
    DatabasePassword: "rootpassword"
    DatabaseUserName: "root"