project_code: "simple-emr"
profile: {{ var.profile }}
region: "eu-west-1"

template_path: simple-emr.py

parameters:
    KeyName: ""
    EMRRole: "EMR_DefaultRole"
    EMRAutoScalingRole: "EMR_AutoScaling_DefaultRole"
    EC2InstanceProfileRole: "EMR_EC2_DefaultRole"
    ReleaseLabel: "emr-5.23.0"

    AdditionalMasterSecurityGroup: ""
    MasterSecurityGroup: ""
    AdditionalSlaveSecurityGroup: ""
    SlaveSecurityGroup: ""
    EC2SubnetId: ""
    EMRLogUri: ""
     
